services:
  - type: web
    name: KraftHeinze
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.enableCORS=false

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5

